### ISSUE TITLE
NOTs not being recognized in the internal features category

### ISSUE THREAD

**Issue by elviscat** [biosemantics/micropie2#20]
For the description sentence:
Endospores are not formed.

What is being parsed under internal features is "endospores". What should be parsed is "not endospores".

For the description sentence:
Gas vesicles and helical or ring-shaped cells are not formed.

What is being parsed under internal features is "vesicles, gas vesicles". What should be parsed is "not vesicles, not gas vesicles"

For the description sentence:
Accumulation of poly-b -hydroxybutyrate granules is not observed

What is being parsed under internal features is "granules, poly-b-hydroxybutyrate". What should be parsed is "not granules, not poly-b-hydroxybutyrate".

etc.

**Comment by danveno** [comment]
negations were handled by applying some rules
