### ISSUE TITLE
Antibiotic resistance characters not being parsed correctly -II

### ISSUE THREAD

**Issue by elviscat** [biosemantics/micropie2#22]
Similar issue with this example:
Susceptible to carbenicillin, chloramphenicol, doxycycline, erythromycin, lincomycin and oleandomycin. Resistant to ampicillin, benzylpenicillin, gentamicin, kanamycin, neomycin, polymyxin B, streptomycin and tetracycline.

All the antibiotics are being parsed under antibiotic sensitivity. What should be parsed are "carbenicillin, chloramphenicol, doxycycline, erythromycin, lincomycin, oleandomycin".

None of the antibiotics are being parsed under antibiotic resistant. What should be parsed are "ampicillin, benzylpenicillin, gentamicin, kanamycin, enomycin, polymyxin B, streptomycin, tetracycline".

**Comment by danveno** [comment]
syntactic rules + term list were used
