### ISSUE TITLE
NOTs not being recognized in the inorganic substances used category - II

### ISSUE THREAD

**Issue by elviscat** [biosemantics/micropie2#25]
I'm not sure why this one is being parsed as it is.

For the description text for Dyadobacter gingengisoli it says:
Nitrate is reduced in aerobic conditions.

What is being parsed under inorganic substances used is "nitrate". This is correct.

What is being parsed under inorganic substances not used is "nitrate". This is not correct - nothing should be parsed here.

**Comment by danveno** [comment]
applied some rules to identify negation
