### ISSUE TITLE
cell shape also picking up fatty acids

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#31]
Hi Jin,

The category cell shape is mistakenly picking up fatty acids (a.k.a. lipids).  For example in the Bacteroidetes output file (Carrine 176 Bacteria descriptions.xlxs):

In the MicroPIE output "asporogenic rods#branched-chain unsaturated#straight-chain unsaturated" the second item "branched-chain unsaturated" and the third item "straight-chain unsaturated" refer to fatty acids.

In the output "iso-branched" this also refers to fatty acids.

In the output "rods#The major long-chain cellular fatty" the phrase "The major long-chain cellular fatty" refers to fatty acids.

in the output "rods#non-hydroxylated 3-hydroxylated long-chain fatty Both non-hydroxylated and 3-hydroxylated long-chain fatty acids" the second item refers to fatty acids.

In the output "bacilli#principal cellular long-chain fatty acids" the second item refers to fatty acids.

In the output "coccobacilli#rods#nonhydroxylated 3-hydroxylated long-chain fatty Both nonhydroxylated and 3-hydroxylated long-chain fatty acids" the third output item refers to fatty acids.

In the output "Rod-shaped cells#straight-chain unsaturated branched-chain unsaturated fatty straight-chain unsaturated and branched-chain unsaturated fatty acids C15:1 iso" the second item refers to fatty acids.

In the output "non-sporulating rods#branched-chain fatty acids 13:0 iso" the second item refers to fatty acids.

In the output "nonmotile fusiforms#nonhydroxylated 3-hydroxylated long-chain fatty Both nonhydroxylated and 3-hydroxylated long-chain fatty acids#saturated straight-chain anteiso-methyl saturated straight-chain and anteiso-methyl branched-chain types" the second item refers to fatty acids.

-Carrine

**Comment by danveno** [comment]
Apply exact term matching strategy for cell shape, which will relief this problem.
