### ISSUE TITLE
cell diameter is a synonym for cell width

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#34]
Hi Jin,

You have separate categories for cell diameter and for cell width, however these are synonyms.  Note that for most taxa that have values returned under cell diameter there are no values returned under cell width.  

Sometimes there are values returned under cell diameter and cell width.  In this case the author was discussing in one phrase cell diameter, but then call it cell width in another phrase or sentence. 

Cell diameter values should just be reported under cell width.

**Comment by danveno** [comment]
When generating the matrix, the cell diameter values will be put into cell width values.
