### ISSUE TITLE
MicroPIE not picking up some cell length values

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#37]
Hi Jin,

MicroPIE isn't picking up cell lengths for some sentence types and is returning empty cells.  For example: 

For the taxon Cellulophaga algicola: "Cells are rod-shaped with either rounded or tapered ends and with cells lengths and widths ranging from 1.5 to 4 and 0.4 to 0.5 µm, respectively"

For the taxon Beliella baltica: "Cells are Gram-negative, rodshaped (width, 0.3–0.5 µm; length, 0.9–3.0 µm) and oxidase- and catalase-positive."

For the taxon Echinicola vietnamensis: "Cells are 0.4–0.56 1.1–2.3 µm."

For the taxon Fibrella aestuarina:  "After 1 day of incubation in SM broth, cells are usually 0.8 µm wide and 1.1–6.9 µm long, but multicellular filaments up to 245 µm long also occur (Fig. 2)."

For the taxon Paraprevotella clara : "Cells are approximately 0.4– 1.3 x0.7–2.2 µm.  "

**Comment by carrineblank** [comment]
Also:
For the taxon Bacteroides merdae: "Cells of the type strain from peptone-yeast extract broth cultures are 1.6 by 3.1 to 12 µm and occur singly or in pairs or short chains."

**Comment by danveno** [comment]
This one is difficult. For the taxon Cellulophaga algicola: "Cells are rod-shaped with either rounded or tapered ends and with cells lengths and widths ranging from 1.5 to 4 and 0.4 to 0.5 µm, respectively".

 "Cells are 0.4–0.56 1.1–2.3 µm." a "x" is missing.

For the others, maybe they are errors of the character prediction or the extraction method. I will check.

**Comment by danveno** [comment]
The extractor about cell size has been updated to address the problems in the following two sentences: "Cells are Gram-negative, rodshaped (width, 0.3–0.5 µm; length, 0.9–3.0 µm) and oxidase- and catalase-positive."  "Cells are approximately 0.4– 1.3 x0.7–2.2 µm. "

The problems about character prediction and the pattern in the first sentence ("respectively") which is difficult for computers to handle automatically will be focused on by the future MicroPIE.
