### ISSUE TITLE
mol% G+C error

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#38]
Hi Jin,

The phrase "Strains with decreased susceptibility to penicillin (> 40 % of strains, including the type strain) produced β-lactamase.  " was interpreted by MicroPIE as having a mol% G+C of >40%.  This sentence has no information about mol% G+C.

**Comment by danveno** [comment]
This seems to be an error about character prediction.

**Comment by carrineblank** [comment]
This is an instance of an error - not a trend.

**Comment by lmoore207** [comment]
is this an easy fix? It is a bad mistake that should be fixed soon if at all possible.

**Comment by danveno** [comment]
This is not easy to fix. This could be attributed to system errors related to imperfection of fundamental algorithms.

**Comment by danveno** [comment]
write a hard code rule according to the cues of g, c, mol, etc.
