### ISSUE TITLE
internal features

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#39]
Hi Jin!

Could we make sure that phrases like "No resting stages" are captured under the character Internal Features?  Right now it is being picked up by cell shape.

**Comment by danveno** [comment]
this term "resting stages" is in the term list of cell shape. Should it be removed and added to internal features?

**Comment by lmoore207** [comment]
I believe that Carrine has provided an updated term list that has these terms under the correct character. Can this issue be marked as resolved?

**Comment by carrineblank** [comment]
Hi all,

I'd rather wait to make sure that the updated term list is going to solve the problem before marking it as resolved.

Thanks!


-Carrine


Carrine E. Blank, PhD
Research Assistant Professor
109A Clapp Science Building
Department of Geosciences
University of Montana
32 Campus Drive
Missoula, MT 59812-1296
406-880-3402 (cell); carrine.blank (Skype); carrine.blank@umontana.edu (email)
http://hs.umt.edu/geosciences/people/research.php?s=Blank1937
________________________________

**Comment by danveno** [comment]
I updated the term lists and applied exact term matching strategy for this character.
