### ISSUE TITLE
extraneous features in motility character

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#40]
Hi Jin:

MicroPIE is picking up extraneous text in the character Motility.

For example: "filaments#non-motile" filaments should be under cell shape and not motility.

For the MicroPIE extracted phrase "non-flagellated short rods#not  Motility" the only thing that should be returned is "non-flagellated#not Motility"

For the extracted phrase "non-flagellated short rods" only "non-flagellated" should be returned.

For Bacteroides thetaiotaomicron the following is returned: "No  motility#motile".  The sentence in the description is: "No motility was observed; Distaso states that this organism is motile; we believe that he observed Brownian movement, which is very active."  So.... this one is a bit tricky.
For the extracted phrase "multicellular filaments#non-motile rods#absent  gliding motility#absent  Flagellar" "multicellular filaments" and "rods" should be under cell shape.

For the output "Numerous filamentous tufts" this should be reported under external features and not motiliy.

For the output "motile cells#uniseriate filaments#immotile filaments#Gram-negative and lack flagella#No  swimming cells#gliding cells#multicellular filaments#flagella" a number of things should be reported in other columns.  "uniseriate filaments" should go under cell shape, filaments under cell shape, Gram-negative under Gram stain type, "multicellular filaments" under cell shape and cell relationships.

Cells that are non-flagellated, but are also motility by gliding are being reported as "non-flagellated#Motile".  I think Hong submitted an issue tracker item on this as well.

**Comment by danveno** [comment]
extraneous features were removed. But the values like " motility by gliding" is a bit difficult. I am wondering whether we should design some fine-grained extractors for each character to deal with some special cases.
