### ISSUE TITLE
internal features picking up some additional characters

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#41]
Hi Jin,

the internal features category is also picking up some characters that belong in other columns.

For example "non-motile and non-spore-forming rods" should return only "non-spore-forming"

"irregular rods#non-sporulating" should return "non-sporulating"

"multicellular filaments" belongs under cell shape and cell relationships (not internal features)

"non-sheathed" is reported under external features.

"branching cells" should be reported under cell shape.

"Gram negative non-sporing non-motile rods" should only return "non-sporing"

"nonsporulating and nonmotile rods 0.24-5 _m wide and 1-23 _m" should only return "nonsporulating"

**Comment by danveno** [comment]
The term list has been updated. And we apply exact term matching rather than phrase matching for this character.
