### ISSUE TITLE
colony phenotypes

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#47]
Hi Jin

Note that optical quality terms such as "dull", "shiny", "glistening", "translucent", and "opaque" are being picked up by both colony texture and colony color or sometimes one but not the other.  These should be only in one column.  Perhaps the most appropriate one is colony color (thinking of the PATO structure), although you might want to ask Hong.

Other issues:

The description sentence: "Colonies on R2A agar are circular, entire, pink and not easily emulsified. " Was extracted as:
Colony shape: "not circular" - should be "circular"
Colony margin: "not entire" - should be "entire"
Colony color: "not pink" - should be "pink"

Under colony color the phrase extracted for the description sentence: "Forms orange colonies." was "forms orange colonies".  Simply the word "orange" would be the most preferable output.

For the description sentence: " Colonies are circular, entirely margined, glistening, butyraceous and orange on MA and do not glide."  Was extracted as:
Colony margin: nothing extracted - should be "entirely margined"
Colony texture: nothing extracted - should be "butyraceous"
Colony color: "not orange" - should be "glistening#orange"

For the description phrase: "circular to slightly irregular with entire to erose margins, low convex, translucent, gray, dull, smooth." Was extracted:
Colony margin: "margins#entire" - should be "entire#erose"
Colony texture: "smooth#dull#translucent#stringy sediment#a smooth" - should be "smooth"
Colony color: "gray" - should be "gray#dull#translucent"

For the description sentence: "Colonies are circular, low convex, shiny with entire edges and 1–3 mm in diameter on marine agar 2216".  Was extracted:
Colony shape: nothing extracted - should be "circular#low convex"

For the description sentence: "Colonies are circular, smooth, low convex, glistening, moderately reddish-orange in colour " Was extracted:
Colony color"moderately reddish-orange" - should be "moderately reddish-orange#glistening"

**Comment by carrineblank** [comment]
Also.... many of the output for colony color is also picking up culture media (e.g. "blood agar", "blood agar plates", "not  media containing hemolyzed blood", "anaerobic blood agar plates", "rabbit laked blood agar colonies", "blood sheep agar", ) - this shouldn't be included under colony color.

**Comment by carrineblank** [comment]
Also... many output cells for colony color (and I've seen it in a few of the other colony columns as well) have additional information about size.  For example, for the description sentence "Colonies on 0.1x TSA (Difco) plates are circular, convex, smooth, cream to pink coloured and 1.0–2.0 mm in diameter after incubation for 3 days at 28 ˚C.  " MicroPIE outputs for colony color "pink coloured and 1.0-2.0 mm#cream" when the correct output should be "pink#cream".

**Comment by danveno** [comment]
the term lists has been updated.
