### ISSUE TITLE
mm and mM units

### ISSUE THREAD

**Issue by lmoore207** [biosemantics/micropie2#50]
The following descriptive sentence: "Typical cells are 0.8–3.0 mm by 0.5–1.5 mm in size." was extracted under NaCl minimum as "0.8 mM#0.5 mM" and under NaCl maximum as "3.0 mM#1.5 mM". So, the context (NaCl or size of cells or colonies) needs to be linked with the mM units in order for the values to be pulled out correctly.
Another example - the sentence "Extraordinarily long cells (7.5–52.4 mm long) occur rarely." extracted "7.5 mM" for NaCl minimum, and "52.4 mM" for NaCl maximum.

**Comment by danveno** [comment]
The former version of MicroPIE convert "mm" to "mM" for normalization. "mM" and "mm" are all normalized to "mm" now.
