### ISSUE TITLE
Error compiling with Maven

### ISSUE THREAD

**Issue by stilianoslouca** [biosemantics/micropie2#53]
When trying to compile MicroPIE using maven (mvn install) I get the following error:
```
[ERROR] micropie2-master/src/main/java/edu/arizona/biosemantics/micropie/nlptool/PhraseParser.java:[223,49] diamond operator is not supported in -source 1.5
[ERROR] (use -source 7 or higher to enable diamond operator)

```
I fixed the problem by adding the following lines within the `<properties>..</properties>` clause, in the POM.xml file:
``<maven.compiler.source>7</maven.compiler.source><maven.compiler.target>7</maven.compiler.target>
``

Using Mac OS 10.10.5, Java Runtime Environment 1.8.0_101, maven 3.3.9.

**Comment by danveno** [comment]
We suggest to use JRE 1.8 because Standford CoreNLP needs it. 
Thank you.
