### ISSUE TITLE
Salinity/Salt relationship to growth

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#66]
For some reason "occur NaCl" is being reported for Salinity/Salt relationship to growth for the following description when there is nothing in the text that relates to NaCl:

Cells are Gram-positive cocci occurring as single cells, in pairs or in short chains. Cells are non-spore-forming and non-motile. Tiny colonies up to 0.2 mm in diameter are formed on Columbia agar supplemented with 5% horse blood at 37 ˚C. Neither pyridoxal hydrochloride nor satellitism is required to support growth. Haemolysis is not observed. Facultatively anaerobic and catalase-negative. Acid is produced from glucose, maltose, pullulan and trehalose. Acid is not produced from L-arabinose, D-arabitol, cyclodextrin, glycogen, lactose, mannitol, melibiose, melezitose, D-raffinose, D-ribose, sucrose, sorbitol, tagatose or D-xylose. Arginine dihydrolase, pyroglutamic acid arylamidase (weak reaction), N-acetylglucosaminidase, ester lipase (C8), leucine arylamidase and urease (weak reaction) activity is detected. Alkaline phosphatase, acid phosphatase, alanyl-phenylalanineproline arylamidase, α-galactosidase, β-galactosidase, β-galacturonidase, β-glucuronidase, glycyl-tryptophan arylamidase, α-mannosidase, β-mannosidase, chymotrypsin, trypsin, α-fucosidase and pyrazinamidase activity is not detected. Aesculin is hydrolysed. Hippurate and gelatin are not hydrolysed. Nitrate is not reduced. The cell wall contains an L-Orn-D-Asp-based, directly cross-linked murein (type A4/3). The G+C content of DNA of the type strain is 37 mol % (Tm). As determined by 16s rRNA gene sequence analysis, the new species belongs to the lactic acid group of bacteria with low DNA G+C contents, and is phylogenetically closely related to A. adiacens and A. elegans, but may be distinguished from the latter two species using traits shown in Table 1. Isolated from minke whale. Habitat not known. The type strain is CCUG 37380T

**Comment by danveno** [comment]
see #73
