### ISSUE TITLE
Question: There is no term-1, (no) term-2, term-3, and term-4. => Is this type suitable for USP?

### ISSUE THREAD

**Issue by elviscat** [biosemantics/micropie2#7]
Example sentence: There is no production of films and spots or phosphatase activity, no liquefaction of coagulated horse serum, and no hydrolysis of esculin or arbutin.
-
Question 1: What keyword can be used in this sentence if we use USP result to extract?
Question 2: Will this kind of sentence be suitable for USP?

**Comment by danveno** [comment]
USP could help. But the performance could be questioned. Some simple rule can work well than USP. We didn't use USP in current MicroPIE.
