### ISSUE TITLE
pH characters incorrectly extracted as NaCl characters

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#71]
For the phrase "Does not grow at 42 ˚C or at pH 4 or 11. Tolerates up to 5.8% NaCl.   " MicroPIE is incorrectly extracting "4" as the NaCl minimum. It is "5.% NaCl|11" as the NaCl maximum - the "5.8%" value is correct, but the "11" value is incorrect.

**Comment by danveno** [comment]
pH and NaCl are corrected.

**Comment by danveno** [comment]
#84
