### ISSUE TITLE
NaCl max/min characters incorrectly being extracted under pH max/min

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#72]
For the sentence "Growth does not occur at 10 and 45°C or in the presence of 6.5% NaCl."  MicroPIE is reporting 0.00% as the pH minimum (this doesn't make any sense, since 1) it is not a pH and 2) this doesn't even make sense as a salt concentration given the sentence).  MicroPIE is also reporting 6.5 % NaCl as the pH maximum.  This is not a pH maximum, but should instead be reported as a NaCl maximum.

**Comment by danveno** [comment]
#84
