### ISSUE TITLE
Problems with "No growth occurs in the absence of NaCl"

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#76]
Growth occurs at NaCl concentrations of 1 to 25%; the NaCl concentration for best growth is 7 to 10%. No growth occurs in the absence of NaCl. 

For this sentence MicroPIE is returning "1%|0 NaCl" for NaCl min.  The correct answer should be more like "1%|not 0 NaCl".

**Comment by danveno** [comment]
A special code is used to handle this case. It may not be an ultimate solution.
