### ISSUE TITLE
Another instance of pH max and min being incorrectly reported as NaCl max and min

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#84]
For the sentence "No growth occurs at pH≤6.5 or pH≥8.0; the pH optimum is 7.5".

MicroPIE is extracting 6.5 as the NaCl minimum (this is a pH minimum, not NaCl min).
MicroPIE is extracting 8.0 as the NaCl maximum (this is a pH max, not NaCl max).

**Comment by danveno** [comment]
A bug is found about inferring the maxinum and mininum values (handling USP values) . NaCl and pH were confused.
