### ISSUE TITLE
Another incorrect value being picked up for NaCl min

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#86]
"Cells are rod-shaped (1.5 –2.3 µm long and 0.6 – 0.9 µm wide) with slightly pointed ends, mostly in pairs. Motile by a single subpolar flagellum. Whitish, lens-shaped colonies in agar shake tubes. Gram-positive, no spore formation. Catalase and oxidase negative, strictly anaerobic. Psychrotolerant, growth at 2 ˚C, growth occurs up to 36 ˚C, temperature optimum at 29 ˚C. pH-range for growth is 5.5 –8.5, optimum at 8.0. Halotolerant growth with NaCl concentrations <4.3%, optimum at 0 –2.7% NaCl. Growth on CO and H2/CO2. Chemoorganotroph, utilizing fructose, glucose, ethanol, ethyleneglycol, glycerol, pyruvate, lactate, betaine as well as methyl groups of methoxylated aromatic compounds for growth during fermentation. Syringic acid fermented to gallic acid and acetate. Requires 0.05% (w/v) yeast extract for growth. Mixotrophic growth on H2/CO2 and syringate. G+C content of DNA is 44.1%. Isolated from sulphide rich anoxic sediment of a brackish fjord at the east coast of Jutland (Denmark). The type strain is SyrA5 (DSM 16427=ATCC BAA-990). The GenBank accession No. for the 16S rRNA gene is AY744449, and for the fthfs genes are DQ152900-DQ152908. "

MicroPIE is picking up 0.05% w/v for the NaCl minimum (shouldn't be picking up anything).

**Comment by carrineblank** [comment]
A similar example:

"Growth on yeast extract (0.01 %) occurs in the presence of ferrous iron (Fe2+) at micromolar concentrations. "

MicroPIE is incorrectly picking up 0.01% as the NaCl min.

**Comment by danveno** [comment]
#85
