### ISSUE TITLE
Additional issue with rRNA sequence similarity being picked up as NaCl min

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#88]
For "Gram-negative rods that are 1.1 µm wide by 1.7 to 3.3 µm long. Flagella are not observed. No spores are formed. This organism grows in a mineral medium but grows more rapidly and abundantly in a medium containing 0.02% yeast extract. The substrates which support growth include H2, formate, methanol, glucose, syringate, pyruvate, lactate, betaine, ethanol, propanol, glycerol, and acetoin. Substrates which do not support growth include fructose, choline, and ethylene glycol. The type strain exhibits 97.0 to 99.3% homology with the previously described strains in the genus Acetobacterium based on an analysis of the 16S rRNA sequence. The closest relatives based on phylogenetic analysis are A. wieringae and A. malicum. Habitat: subsurface sandstone. Type strain: CN-E, which has been deposited in the Subsurface Microbial Culture Collection as strain SMCC/W 751. "

MicroPIE is incorrectly picking up 97% (no additional units) for the NaCl min.  It should be picking up nothing.

MicroPIE is incorrectly picking up 99.3% for the NaCl max.  It should be picking up nothing.

**Comment by danveno** [comment]
#85
