### ISSUE TITLE
Extraneous NaCl min value

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#89]
For "From sludge obtained from the sewage digester plant in Stuttgart-Mohringen a strictly anaerobic bacterium was enriched and isolated with methyl chloride as the energy source.  The isolate, which was tentatively called strain MC, was nonmotile, gram-positive, and occurred as elongated cocci arranged in chains. Cells of strain MC formed about 3 mol of acetate per 4 mol of CH3Cl consumed, indicating that the organism was a homoacetogenic bacterium fermenting methyl chloride plus CO2 according to: 4 CH3Cl + 2 CO2 + 2 H2O → 3 CH3COO- +7H+ + 4Cl- . The organism grew with 2-3% methyl chloride in the gas phase at a doubling time of near 30 h.  Dichloromethane was not utilized. The bacterium also grew on carbon monoxide, I-t2 plus CO2, and methoxylated aromatic compounds.  Optimal growth with methyl chloride was observed at 25˚C and pH 7.3-7.7.  The G + C-content of the DNA was 47.5 ± 1.5%.  The methyl chloride conversion appeared to be inducible, since H2 plus CO2-grown cells lacked this ability. From the morphological and physiological characteristics, the isolate could not be affiliated to a known species. "

MicroPIE is incorrectly picking up 2% (no other units) as the NaCl min.  It should be picking up nothing.

**Comment by danveno** [comment]
#85
