### ISSUE TITLE
Not picking up an NaCl max

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#91]
For "NaCl growth sensitivity is variable; no growth occurs in the presence of 5% NaCl"

MicroPIE isn't picking up anything for NaCl min or max.  The NaCl max should be 5% NaCl.

**Comment by danveno** [comment]
MicroPIE identifies 5|%|NaCl, however, it doesnot treat it as a maximum value. Can we make the hypothesis that "no growth occurs in the presence of " is saying a maxinum value?

**Comment by carrineblank** [comment]
I looked at the 1500 Firmicutes descriptions, and I believe we CAN make the assumption that this is a maximum value.
________________________________

**Comment by danveno** [comment]
Considered this rule in the extractor
