### ISSUE TITLE
pH range being picked up as a pH min

### ISSUE THREAD

**Issue by carrineblank** [biosemantics/micropie2#96]
For "pH range for growth is 6.0–8.0, optimum 7.0. "

MicroPIE is incorrectly picking up 6.0-8.0 as the pH min.
The correct pH min should be 6.0.
The correct pH max should be 8.0.
(MicroPIE is CORRECTLY picking up 7.0 as the pH opt.)

**Comment by danveno** [comment]
Input it as a single sentence, the results seem to be right.
